#!/bin/bash
#PBS -l nodes=16:ppn=1,arch=x86_64
#PBS -l walltime=00:00:59
#PBS -o global_pi.out
#PBS -j oe
#PBS -N global_pi
#PBS -A lc_an2
WORK_HOME=/home/rcf-proj2/an2/chiehwen
cd $WORK_HOME
np=$(cat $PBS_NODEFILE | wc -l)
mpirun -np $np -machinefile $PBS_NODEFILE ./global_pi
mpirun -np 8 -machinefile $PBS_NODEFILE ./global_pi
mpirun -np 4 -machinefile $PBS_NODEFILE ./global_pi
mpirun -np 2 -machinefile $PBS_NODEFILE ./global_pi
mpirun -np 1 -machinefile $PBS_NODEFILE ./global_pi
